---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: windows-latest
    steps:
      - name: Login To Docker Hub
        user: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check Out
        user: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"